# Streamlit Configuration for Cloud Deployment
[theme]

backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
